2020-03-13 21:15:22,345 ERROR: (message)s [ in /home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kaustuv/Documents/project/Oauth2/app/routes.py", line 75, in user
    return render_template('user.html', user=user,posts=posts)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/kaustuv/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/kaustuv/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/kaustuv/Documents/project/Oauth2/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kaustuv/Documents/project/Oauth2/app/templates/base.html", line 76, in top-level template code
    {% block content %}{% endblock %}
  File "/home/kaustuv/Documents/project/Oauth2/app/templates/user.html", line 17, in block "content"
    <p><a href="{{ url_for('unfollow', username=user.username) }}">Unfollow</a></p>
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/kaustuv/.local/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'unfollow' with values ['username']. Did you mean 'follow' instead?
2020-03-13 21:15:23,601 ERROR: (message)s [ in /home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kaustuv/Documents/project/Oauth2/app/routes.py", line 75, in user
    return render_template('user.html', user=user,posts=posts)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/kaustuv/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/kaustuv/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/kaustuv/Documents/project/Oauth2/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kaustuv/Documents/project/Oauth2/app/templates/base.html", line 76, in top-level template code
    {% block content %}{% endblock %}
  File "/home/kaustuv/Documents/project/Oauth2/app/templates/user.html", line 17, in block "content"
    <p><a href="{{ url_for('unfollow', username=user.username) }}">Unfollow</a></p>
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/kaustuv/.local/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'unfollow' with values ['username']. Did you mean 'follow' instead?
2020-03-13 21:26:27,592 INFO: (message)s [ in /home/kaustuv/Documents/project/Oauth2/app/__init__.py:41]
2020-03-13 21:28:07,580 ERROR: (message)s [ in /home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kaustuv/Documents/project/Oauth2/app/routes.py", line 75, in user
    return render_template('user.html', user=user,posts=posts)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/kaustuv/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/kaustuv/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/kaustuv/Documents/project/Oauth2/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kaustuv/Documents/project/Oauth2/app/templates/base.html", line 76, in top-level template code
    {% block content %}{% endblock %}
  File "/home/kaustuv/Documents/project/Oauth2/app/templates/user.html", line 17, in block "content"
    <p><a href="{{ url_for('unfollow', username=user.username) }}">Unfollow</a></p>
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kaustuv/.local/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/kaustuv/.local/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'unfollow' with values ['username']. Did you mean 'follow' instead?
